/**
 * Danh sách dữ liệu sản phẩm Đồ chơi (Mô phỏng MyKingdom - Vương quốc đồ chơi)
 */
const PRODUCTS_DATA = [
  {
    id: 'prod-001',
    name: 'Đồ Chơi Lắp Ráp LEGO Star Wars X-Wing Fighter 75301',
    brand: 'LEGO',
    category: 'Lắp ráp',
    ageGroup: '6-11 tuổi',
    price: 1399000,
    originalPrice: 1899000,
    discountPercent: 26,
    rating: 4.9,
    reviewsCount: 128,
    image: 'https://images.unsplash.com/photo-1585366119957-e9730b6d0f60?w=600&auto=format&fit=crop&q=80',
    description: 'Bộ lắp ráp chiến hạm X-Wing Fighter huyền thoại từ series Star Wars với 474 chi tiết, đi kèm minifigure Luke Skywalker, Công chúa Leia và R2-D2. Giúp bé phát triển tư duy sáng tạo & khả năng kiên nhẫn.',
    isFlashSale: true,
    stockLeft: 4,
    totalStock: 20,
    badge: 'HOT SALE',
    badgeType: 'danger',
    specs: {
      material: 'Nhựa ABS cao cấp',
      origin: 'Đan Mạch',
      pieces: 474,
      dimensions: '31 x 28 x 8 cm'
    }
  },
  {
    id: 'prod-002',
    name: 'Bộ Đường Đua Hot Wheels Siêu Tốc Đột Phá GKP45',
    brand: 'Hot Wheels',
    category: 'Xe mô hình',
    ageGroup: '3-5 tuổi',
    price: 649000,
    originalPrice: 899000,
    discountPercent: 28,
    rating: 4.8,
    reviewsCount: 95,
    image: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?w=600&auto=format&fit=crop&q=80',
    description: 'Bộ đường đua tốc độ cực đỉnh với bệ phóng thần tốc và 1 xe Hot Wheels đúc kim loại (Die-cast) độc quyền. Bé thỏa sức thách thức giới hạn tốc độ và tạo hiệu ứng nhào lộn ngoạn mục.',
    isFlashSale: true,
    stockLeft: 8,
    totalStock: 25,
    badge: 'FLASH SALE',
    badgeType: 'warning',
    specs: {
      material: 'Kim loại & Nhựa cao cấp',
      origin: 'Mỹ',
      pieces: 12,
      dimensions: '45 x 30 x 10 cm'
    }
  },
  {
    id: 'prod-003',
    name: 'Búp Bê Barbie Ngôi Nhà Mơ Ước Dreamhouse HMX10',
    brand: 'Barbie',
    category: 'Búp bê',
    ageGroup: '6-11 tuổi',
    price: 3299000,
    originalPrice: 3999000,
    discountPercent: 18,
    rating: 5.0,
    reviewsCount: 64,
    image: 'https://images.unsplash.com/photo-1566576912321-d58ddd7a6088?w=600&auto=format&fit=crop&q=80',
    description: 'Búp bê Barbie sở hữu tủ đồ thời trang cực đỉnh với bộ đầm lộng lẫy và phụ kiện trang sức đi kèm. Thiết kế tinh xảo, chất liệu an toàn tuyệt đối cho bé gái tự do sáng tạo câu chuyện thần tiên.',
    isFlashSale: false,
    stockLeft: 15,
    totalStock: 30,
    badge: 'NEW',
    badgeType: 'success',
    specs: {
      material: 'Nhựa mềm & Vải cao cấp',
      origin: 'Mỹ',
      pieces: 8,
      dimensions: '30 x 15 x 6 cm'
    }
  },
  {
    id: 'prod-004',
    name: 'Đồ Chơi Giáo Dục Robot STEM Lập Trình Thông Minh',
    brand: 'STEM Toys',
    category: 'Đồ chơi giáo dục',
    ageGroup: '12+ tuổi',
    price: 1150000,
    originalPrice: 1500000,
    discountPercent: 23,
    rating: 4.7,
    reviewsCount: 42,
    image: 'https://images.unsplash.com/photo-1535378917042-10a22c95931a?w=600&auto=format&fit=crop&q=80',
    description: 'Robot thông minh lập trình qua ứng dụng điện thoại, cảm biến tránh vật cản và nhảy theo nhạc. Phát triển tư duy logic, tư duy toán học và công nghệ khoa học STEM.',
    isFlashSale: true,
    stockLeft: 3,
    totalStock: 15,
    badge: 'HOT SALE',
    badgeType: 'danger',
    specs: {
      material: 'Nhựa linh kiện điện tử',
      origin: 'Nhật Bản',
      pieces: 1,
      dimensions: '20 x 18 x 25 cm'
    }
  },
  {
    id: 'prod-005',
    name: 'Đồ Chơi Đất Nặn Play-Doh Tháp Bánh Sinh Nhật Cực Đại',
    brand: 'Play-Doh',
    category: 'Đồ chơi giáo dục',
    ageGroup: '3-5 tuổi',
    price: 499000,
    originalPrice: 650000,
    discountPercent: 23,
    rating: 4.9,
    reviewsCount: 210,
    image: 'https://images.unsplash.com/photo-1513542789411-b6a5d4f31634?w=600&auto=format&fit=crop&q=80',
    description: 'Bộ bột nặn làm bánh sinh nhật với 5 hũ màu bột nặn Play-Doh lúa mì tự nhiên thơm dịu, 20+ khuôn tạo hình sinh động cho bé làm đầu bếp nhí trổ tài sáng tạo.',
    isFlashSale: false,
    stockLeft: 40,
    totalStock: 50,
    badge: 'BÁN CHẠY',
    badgeType: 'info',
    specs: {
      material: 'Bột lúa mì tự nhiên',
      origin: 'Mỹ',
      pieces: 24,
      dimensions: '33 x 30 x 8 cm'
    }
  },
  {
    id: 'prod-006',
    name: 'Xe Điều Khiển Từ Xa Địa Hình Rock Crawler 4WD 1:14',
    brand: 'Hot Wheels',
    category: 'Xe mô hình',
    ageGroup: '6-11 tuổi',
    price: 790000,
    originalPrice: 1100000,
    discountPercent: 28,
    rating: 4.8,
    reviewsCount: 88,
    image: 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?w=600&auto=format&fit=crop&q=80',
    description: 'Xe leo núi 2 cầu độc lập, giảm xóc lò xo siêu vượt địa hình đá, cát, cỏ. Tốc độ tối đa 20km/h với tay cầm điều khiển sóng 2.4GHz không nhiễu.',
    isFlashSale: true,
    stockLeft: 5,
    totalStock: 18,
    badge: 'FLASH SALE',
    badgeType: 'warning',
    specs: {
      material: 'Hợp kim nhôm & Nhựa ABS',
      origin: 'Đài Loan',
      pieces: 3,
      dimensions: '35 x 22 x 18 cm'
    }
  },
  {
    id: 'prod-007',
    name: 'Đồ Chơi Thả Hình Khối Gỗ Fisher-Price Nhận Biết Màu Sắc',
    brand: 'Fisher-Price',
    category: 'Đồ chơi giáo dục',
    ageGroup: '0-2 tuổi',
    price: 299000,
    originalPrice: 420000,
    discountPercent: 29,
    rating: 4.9,
    reviewsCount: 156,
    image: 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=600&auto=format&fit=crop&q=80',
    description: 'Hộp thả hình khối gỗ tự nhiên sơn phủ không độc hại. Giúp trẻ sơ sinh từ 6-24 tháng phát triển kỹ năng cầm nắm, nhận biết hình học cơ bản và màu sắc.',
    isFlashSale: false,
    stockLeft: 22,
    totalStock: 40,
    badge: 'BEST FOR BABY',
    badgeType: 'success',
    specs: {
      material: 'Gỗ cao su tự nhiên',
      origin: 'Thái Lan',
      pieces: 10,
      dimensions: '15 x 15 x 15 cm'
    }
  },
  {
    id: 'prod-008',
    name: 'Đồ Chơi Lắp Ráp LEGO City Trạm Cảnh Sát Trung Tâm 60316',
    brand: 'LEGO',
    category: 'Lắp ráp',
    ageGroup: '6-11 tuổi',
    price: 1850000,
    originalPrice: 2299000,
    discountPercent: 20,
    rating: 4.9,
    reviewsCount: 77,
    image: 'https://images.unsplash.com/photo-1560969184-10fe8719e047?w=600&auto=format&fit=crop&q=80',
    description: 'Bộ trạm cảnh sát 3 tầng hiện đại tích hợp xe rác bắt cướp, trực quạt cứu hộ và 5 nhân vật minifigures TV series LEGO City. Kích thích trí tưởng tượng vô hạn.',
    isFlashSale: false,
    stockLeft: 12,
    totalStock: 20,
    badge: 'KHUYÊN DÙNG',
    badgeType: 'primary',
    specs: {
      material: 'Nhựa ABS an toàn',
      origin: 'Đan Mạch',
      pieces: 668,
      dimensions: '48 x 37 x 9 cm'
    }
  },
  {
    id: 'prod-009',
    name: 'Gấu Bông Teddy Khổng Lồ 1M2 Mềm Mịn Cao Cấp',
    brand: 'Plushies',
    category: 'Gấu bông',
    ageGroup: '3-5 tuổi',
    price: 520000,
    originalPrice: 750000,
    discountPercent: 31,
    rating: 4.9,
    reviewsCount: 310,
    image: 'https://images.unsplash.com/photo-1559454403-b8fb88521f11?w=600&auto=format&fit=crop&q=80',
    description: 'Chú gấu bông cao 1.2 mét nhồi bông gòn 7D 100% kháng khuẩn, lông nhung mềm mịn êm ái. Món quà ấm áp tuyệt vời dành tặng bé cưng.',
    isFlashSale: true,
    stockLeft: 6,
    totalStock: 30,
    badge: 'BESTSELLER',
    badgeType: 'danger',
    specs: {
      material: 'Lông nhung & Bông 7D',
      origin: 'Hàn Quốc',
      pieces: 1,
      dimensions: '120 cm'
    }
  },
  {
    id: 'prod-010',
    name: 'Bộ Đồ Chơi Cờ Tỷ Phú Monopoly Vietnam Edition',
    brand: 'Board Game',
    category: 'Đồ chơi giáo dục',
    ageGroup: '12+ tuổi',
    price: 399000,
    originalPrice: 499000,
    discountPercent: 20,
    rating: 4.8,
    reviewsCount: 145,
    image: 'https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?w=600&auto=format&fit=crop&q=80',
    description: 'Trò chơi cờ tỷ phú phiên bản địa danh Việt Nam nổi tiếng. Trò chơi trí tuệ kinh điển gắn kết cả gia đình vào những dịp cuối tuần vui vẻ.',
    isFlashSale: false,
    stockLeft: 30,
    totalStock: 50,
    badge: 'FAMILY FAVORITE',
    badgeType: 'info',
    specs: {
      material: 'Giấy cứng & Nhựa',
      origin: 'Mỹ',
      pieces: 1,
      dimensions: '40 x 27 x 5 cm'
    }
  },
  {
    id: 'prod-011',
    name: 'Robot Transformers Optimus Prime Biến Hình 2 Trong 1',
    brand: 'Transformers',
    category: 'Lắp ráp',
    ageGroup: '6-11 tuổi',
    price: 890000,
    originalPrice: 1190000,
    discountPercent: 25,
    rating: 4.7,
    reviewsCount: 89,
    image: 'https://images.unsplash.com/photo-1608889825205-eebdb9fc5806?w=600&auto=format&fit=crop&q=80',
    description: 'Robot thủ lĩnh Optimus Prime có khả năng biến hình linh hoạt thành xe đầu kéo hùng vĩ chỉ với 18 bước thao tác mượt mà.',
    isFlashSale: false,
    stockLeft: 10,
    totalStock: 25,
    badge: 'HOT TRONG TUẦN',
    badgeType: 'warning',
    specs: {
      material: 'Nhựa đúc chịu lực',
      origin: 'Mỹ',
      pieces: 1,
      dimensions: '28 x 20 x 10 cm'
    }
  },
  {
    id: 'prod-012',
    name: 'Súng Đồ Chơi Nerf Elite 2.0 Commander RD-6 Bắn Đạn Mút',
    brand: 'Nerf',
    category: 'Đồ chơi vận động',
    ageGroup: '6-11 tuổi',
    price: 450000,
    originalPrice: 599000,
    discountPercent: 25,
    rating: 4.8,
    reviewsCount: 112,
    image: 'https://images.unsplash.com/photo-1595433707802-6b2626ef1c91?w=600&auto=format&fit=crop&q=80',
    description: 'Súng bắn đạn xốp xốp an toàn với băng đạn xoay 6 viên. Tầm bắn xa tới 27m, kèm theo 12 xốp đạn Nerf chính hãng.',
    isFlashSale: true,
    stockLeft: 7,
    totalStock: 35,
    badge: 'FLASH SALE',
    badgeType: 'danger',
    specs: {
      material: 'Nhựa ABS & Xốp an toàn',
      origin: 'Mỹ',
      pieces: 13,
      dimensions: '36 x 24 x 6 cm'
    }
  }
];

// Danh mục filter sẵn
const CATEGORIES = ['Tất cả', 'Lắp ráp', 'Xe mô hình', 'Búp bê', 'Đồ chơi giáo dục', 'Gấu bông', 'Đồ chơi vận động'];
const BRANDS = ['Tất cả', 'LEGO', 'Hot Wheels', 'Barbie', 'STEM Toys', 'Play-Doh', 'Fisher-Price', 'Transformers', 'Nerf'];
const AGE_GROUPS = ['Tất cả', '0-2 tuổi', '3-5 tuổi', '6-11 tuổi', '12+ tuổi'];
